### ISSUE TITLE
How to convert a .safetensors model

### ISSUE THREAD

**Issue by ZTMIDGO** [Amblyopius/Stable-Diffusion-ONNX-FP16#19]
I tried converting the .safetensors model, but couldn't

The source of the model is civitai

https://civitai.com/models/14171/cutegirlmix4

I use v1-inference.yaml

global_step key not found in model
Traceback (most recent call last):
  File "D:\python\diffusion-convert-fp32\conv_sd_to_onnx.py", line 523, in <module>
    pl = load_pipeline_from_original_stable_diffusion_ckpt(
  File "D:\python\diffusion-convert-fp32\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1137, in load_pipeline_from_original_stable_diffusion_ckpt
    converted_unet_checkpoint = convert_ldm_unet_checkpoint(
  File "D:\python\diffusion-convert-fp32\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 380, in convert_ldm_unet_checkpoint
    new_checkpoint["time_embedding.linear_1.weight"] = unet_state_dict["time_embed.0.weight"]
KeyError: 'time_embed.0.weight'

**Comment by Amblyopius** [comment]
It's a LORA model which currently does not work yet with my tools.

**Comment by ZTMIDGO** [comment]
> It's a LORA model which currently does not work yet with my tools.

Thanks, I still have some questions, how do I convert the VAE model of https://huggingface.co/stabilityai/sd-vae-ft-mse-original/tree/main to onnx

**Comment by Amblyopius** [comment]
Hi, as per the documentation. You need to use --vae_path "stabilityai/sd-vae-ft-mse" which points to the same VAE but in diffusers format.
