### ISSUE TITLE
Error when converting runwayml/stable-diffusion-v1-5

### ISSUE THREAD

**Issue by yx-chan131** [Amblyopius/Stable-Diffusion-ONNX-FP16#35]
My command:
`python conv_sd_to_onnx.py --model_path "runwayml/stable-diffusion-v1-5" --output_path "./model/sd1_5base"`

Error:

`(sd) PS D:\stable-diffusion\Stable-Diffusion-ONNX-FP16> python conv_sd_to_onnx.py --model_path "runwayml/stable-diffusion-v1-5" --output_path "./model/sd1_5base"
text_encoder\model.safetensors not found
Downloading (…)e6a/unet/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 743/743 [00:00<?, ?B/s]
C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LiAng\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Fetching 15 files:  47%|██████████████████████████████████████████████████████▏                                                             | 7/15 [00:11<00:12,  1.62s/it]
Traceback (most recent call last):
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\urllib3\connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\http\client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\urllib3\util\util.py", line 39, in reraise
    raise value
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\urllib3\connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\urllib3\connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\stable-diffusion\Stable-Diffusion-ONNX-FP16\conv_sd_to_onnx.py", line 619, in <module>
    pl = StableDiffusionPipeline.from_pretrained(args.model_path,
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 908, in from_pretrained
    cached_folder = cls.download(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1349, in download
    cached_folder = snapshot_download(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\_snapshot_download.py", line 235, in snapshot_download
    thread_map(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\_snapshot_download.py", line 211, in _inner_hf_hub_download
    return hf_hub_download(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\file_download.py", line 1364, in hf_hub_download
    http_get(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\file_download.py", line 505, in http_get
    r = _request_wrapper(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\file_download.py", line 442, in _request_wrapper
    return http_backoff(
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\huggingface_hub\utils\_http.py", line 212, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\LiAng\miniconda3\envs\sd\lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10.0)`

**Comment by Amblyopius** [comment]
You are having internet connection issues while downloading from HF. Unfortunately that's very hard to troubleshoot for me. Alternatively you could try to first download the models via any other means and then point the conversion script to the local directory where the model is stored once you're sure it has been successfully downloaded.
