### ISSUE TITLE
Failed to export stable difussion model with error UnsupportedOperatorError

### ISSUE THREAD

**Issue by marty1885** [Amblyopius/Stable-Diffusion-ONNX-FP16#36]
Hi, I tried to export SD into ONNX but ran into ONNX conversion error when I run the export comment documented in README?

How can I solve it?

```
> python3 conv_sd_to_onnx.py --model_path "stabilityai/stable-diffusion-2-1-base" --output_path "./model/sd2_1base-fp16" --fp16
...
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
None
<Set verbose=True to see more details>


Traceback (most recent call last):
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/conv_sd_to_onnx.py", line 658, in <module>
    convert_models(pl, args.output_path,
  File "/home/marty/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/conv_sd_to_onnx.py", line 375, in convert_models
    onnx_export(
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/conv_sd_to_onnx.py", line 125, in onnx_export
    export(
  File "/home/marty/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/marty/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/marty/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/home/marty/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/marty/.local/lib/python3.10/site-packages/torch/onnx/utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

**Comment by Amblyopius** [comment]
Are you sure you followed all the instructions? The most likely cause is that you have the wrong version of torch. Exporting sdp attention to ONNX works only from 2.1 onwards and you need to install nightly for that.

**Comment by marty1885** [comment]
Ah right. My bad. I should have known better. I followed the instructions as described in the README and using nightly pytorch. I still get this:

```
/home/marty/Documents/Stable-Diffusion-ONNX-FP16/sd_env/lib/python3.10/site-packages/diffusers/models/autoencoder_kl.py:193: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not return_dict:
======== Diagnostic Run torch.onnx.export version 2.1.0.dev20230617+cpu ========
verbose: False, log level: 40
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

/home/marty/Documents/Stable-Diffusion-ONNX-FP16/sd_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:65: UserWarning: Specified provider 'DmlExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  warnings.warn(
Traceback (most recent call last):
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/conv_sd_to_onnx.py", line 658, in <module>
    convert_models(pl, args.output_path,
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/sd_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/conv_sd_to_onnx.py", line 431, in convert_models
    unet=OnnxRuntimeModel.from_pretrained(output_path / "unet",
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/sd_env/lib/python3.10/site-packages/diffusers/pipelines/onnx_utils.py", line 205, in from_pretrained
    return cls._from_pretrained(
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/sd_env/lib/python3.10/site-packages/diffusers/pipelines/onnx_utils.py", line 172, in _from_pretrained
    model = OnnxRuntimeModel.load_model(
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/sd_env/lib/python3.10/site-packages/diffusers/pipelines/onnx_utils.py", line 77, in load_model
    return ort.InferenceSession(path, providers=[provider], sess_options=sess_options)
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/sd_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/marty/Documents/Stable-Diffusion-ONNX-FP16/sd_env/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Failed to find kernel for GroupNorm(1) (node GroupNorm_0). Kernel not found
```

**Comment by Amblyopius** [comment]
Hi, that should only happen if a tuned model is being loaded on ONNX Runtime CPU rather than ONNX Runtime DirectML. Let me check if the online version is missing an update that may cause it.

**Comment by Amblyopius** [comment]
Checked the current version and it should be fine. At line 431/432 there should be this:
        unet=OnnxRuntimeModel.from_pretrained(output_path / "unet",
            low_cpu_mem_usage=False, provider="DmlExecutionProvider"),
Only if provider="DmlExecutionProvider" is missing from 432 I can imagine it's happening. In that case you would be on an older version than what's on GitHub.

What GPU are you trying this on? I haven't seen the problem before but I wouldn't put it past Microsoft to not guarantee ORT DirectML supports custom ops on every card ...

**Comment by Amblyopius** [comment]
Should work then as that's what I'm using. One other option: are you on the latest driver? Another potential issue might be it depends on drivers.

**Comment by marty1885** [comment]
I don't know what happened. I reinstalled my OS due to drive failure. Now the issue disappears. Thanks for the help. Still not sure what happened tho
